### ISSUE TITLE
最原始方案出处

### ISSUE THREAD

**Issue by yulingtianxia** [macacajs/iosHookViewId#5]
https://github.com/yulingtianxia/TBUIAutoTest
http://yulingtianxia.com/blog/2016/03/28/Add-UITest-Label-for-UIAutomation/

**Comment by kobewu** [comment]
哈哈，连代码里面的注释都没删，6666。。。

**Comment by SatanWoo** [comment]
这直接就是赤裸裸的抄袭了吧。。

**Comment by Yinxl** [comment]
你好 这个思路确实来源于原作者的那篇博客，因为当时没有找到源码，所以自己参考文章里的实现方式写了一份，对于给原作者造成的困扰深表抱歉，我把相关引用放在readme里，请见谅~
